### ISSUE TITLE
Cannot compile with GCC 5.1

### ISSUE THREAD

**Issue by fe56** [casacore/casacore#172]
Hi,

as the title says. I am getting errors when trying to compile with:
gcc --version
gcc (GCC) 5.1.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Is it supposed to work with GCC 5.1. Has anyone tested it?

It worked with earlier versions but the package management on the new cluster only provides the dependencies with the new toolchain.

Cheers,
Stefan

Error is as follows:
make 
[  0%] Building CXX object casa/CMakeFiles/casa_casa.dir/Arrays/ArrayOpsDiffShapes.cc.o
In file included from /homea/htb00/htb003/source/casacore/casacore/casa/BasicMath/Math.h:33:0,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayMath.h:32,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayOpsDiffShapes.h:32,
                 from /homea/htb00/htb003/source/casacore/casa/Arrays/ArrayOpsDiffShapes.cc:27:
/homea/htb00/htb003/source/casacore/casacore/casa/math.h: In function 'casa::Float casa::pow(casa::Float, casa::Float)':
/homea/htb00/htb003/source/casacore/casacore/casa/math.h:90:39: error: 'casa::Float casa::pow(casa::Float, casa::Float)' conflicts with a previous declaration
    inline Float pow(Float f1, Float f2)
                                       ^
In file included from /homea/htb00/htb003/source/casacore/casacore/casa/math.h:52:0,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/BasicMath/Math.h:33,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayMath.h:32,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayOpsDiffShapes.h:32,
                 from /homea/htb00/htb003/source/casacore/casa/Arrays/ArrayOpsDiffShapes.cc:27:
/usr/local/software/jureca/Stage2/software/Core/GCC/5.1.0/include/c++/5.1.0/cmath:407:3: note: previous declaration 'float std::pow(float, float)'
   pow(float __x, float __y)
   ^
In file included from /homea/htb00/htb003/source/casacore/casacore/casa/BasicMath/Math.h:33:0,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayMath.h:32,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayOpsDiffShapes.h:32,
                 from /homea/htb00/htb003/source/casacore/casa/Arrays/ArrayOpsDiffShapes.cc:27:
/homea/htb00/htb003/source/casacore/casacore/casa/math.h: At global scope:
/homea/htb00/htb003/source/casacore/casacore/casa/math.h:91:52: warning: extra ';' [-Wpedantic]
      { return Float(pow(Double(f1), Double(f2))); };
                                                    ^
In file included from /homea/htb00/htb003/source/casacore/casacore/casa/BasicSL/Complex.h:36:0,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/BasicMath/Functors.h:33,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayMath.h:33,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayOpsDiffShapes.h:32,
                 from /homea/htb00/htb003/source/casacore/casa/Arrays/ArrayOpsDiffShapes.cc:27:
/homea/htb00/htb003/source/casacore/casacore/casa/complex.h:61:12: error: 'float std::pow(float, float)' conflicts with a previous declaration
 using std::pow;
            ^
In file included from /homea/htb00/htb003/source/casacore/casacore/casa/BasicMath/Math.h:33:0,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayMath.h:32,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayOpsDiffShapes.h:32,
                 from /homea/htb00/htb003/source/casacore/casa/Arrays/ArrayOpsDiffShapes.cc:27:
/homea/htb00/htb003/source/casacore/casacore/casa/math.h:90:17: note: previous declaration 'casa::Float casa::pow(casa::Float, casa::Float)'
    inline Float pow(Float f1, Float f2)
                 ^
In file included from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayMath.h:34:0,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayOpsDiffShapes.h:32,
                 from /homea/htb00/htb003/source/casacore/casa/Arrays/ArrayOpsDiffShapes.cc:27:
/homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Array.h:328:13: error: wrong number of template arguments (1, should be 2)
     vector<T> tovector() const;
             ^
In file included from /homea/htb00/htb003/source/casacore/casacore/casa/aips.h:41:0,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayOpsDiffShapes.h:31,
                 from /homea/htb00/htb003/source/casacore/casa/Arrays/ArrayOpsDiffShapes.cc:27:
/homea/htb00/htb003/source/casacore/casacore/casa/aipsdef.h:108:71: note: provided for 'template<class T, class U> class vector'
 #define WHATEVER_VECTOR_FORWARD_DEC template <class T, class U> class vector
                                                                       ^
/homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Array.h:41:1: note: in expansion of macro 'WHATEVER_VECTOR_FORWARD_DEC'
 WHATEVER_VECTOR_FORWARD_DEC;
 ^
In file included from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Vector2.tcc:32:0,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Vector.h:325,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayUtil.h:34,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayLogical.tcc:32,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayLogical.h:453,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/MaskedArray.tcc:33,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/MaskedArray.h:738,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Array.tcc:32,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Array.h:842,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayMath.h:34,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayOpsDiffShapes.h:32,
                 from /homea/htb00/htb003/source/casacore/casa/Arrays/ArrayOpsDiffShapes.cc:27:
/homea/htb00/htb003/source/casacore/casacore/casa/stdvector.h:39:12: error: 'vector' is already declared in this scope
 using std::vector;
            ^
In file included from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Vector.h:325:0,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayUtil.h:34,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayLogical.tcc:32,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayLogical.h:453,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/MaskedArray.tcc:33,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/MaskedArray.h:738,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Array.tcc:32,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Array.h:842,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayMath.h:34,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayOpsDiffShapes.h:32,
                 from /homea/htb00/htb003/source/casacore/casa/Arrays/ArrayOpsDiffShapes.cc:27:
/homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Vector2.tcc:38:1: error: prototype for 'casa::Vector<T>::Vector(const std::vector<U, V>&)' does not match any in class 'casa::Vector<T>'
 Vector<T>::Vector(const vector<U, V> &other)
 ^
In file included from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayUtil.h:34:0,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayLogical.tcc:32,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayLogical.h:453,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/MaskedArray.tcc:33,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/MaskedArray.h:738,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Array.tcc:32,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Array.h:842,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayMath.h:34,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayOpsDiffShapes.h:32,
                 from /homea/htb00/htb003/source/casacore/casa/Arrays/ArrayOpsDiffShapes.cc:27:
/homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Vector.h:147:5: error: candidates are: template<class T> template<class Iterator> casa::Vector<T>::Vector(Iterator, size_t, int)
     Vector(Iterator first, size_t size, int dummy);
     ^
/homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Vector.h:138:9: error:                 template<class T> template<class U, class V> casa::Vector<T>::Vector(const vector<U, V>&)
         Vector(const vector<U, V> &other);
         ^
In file included from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Vector.h:324:0,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayUtil.h:34,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayLogical.tcc:32,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayLogical.h:453,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/MaskedArray.tcc:33,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/MaskedArray.h:738,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Array.tcc:32,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Array.h:842,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayMath.h:34,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayOpsDiffShapes.h:32,
                 from /homea/htb00/htb003/source/casacore/casa/Arrays/ArrayOpsDiffShapes.cc:27:
/homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Vector.tcc:138:1: error:                 casa::Vector<T>::Vector(const casa::IPosition&, const T*)
 Vector<T>::Vector(const IPosition &shape, const T *storage)
 ^
/homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Vector.tcc:130:1: error:                 casa::Vector<T>::Vector(const casa::IPosition&, T*, casa::StorageInitPolicy)
 Vector<T>::Vector(const IPosition &shape, T *storage, 
 ^
/homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Vector.tcc:119:19: error:                 casa::Vector<T>::Vector(const casa::Array<T>&)
 template<class T> Vector<T>::Vector(const Array<T> &other)
                   ^
/homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Vector.tcc:110:19: error:                 casa::Vector<T>::Vector(const casa::Vector<T>&)
 template<class T> Vector<T>::Vector(const Vector<T> &other)
                   ^
/homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Vector.tcc:80:19: error:                 casa::Vector<T>::Vector(const casa::Block<T>&)
 template<class T> Vector<T>::Vector(const Block<T> &other)
                   ^
/homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Vector.tcc:73:19: error:                 casa::Vector<T>::Vector(const casa::Block<T>&, casa::Int64)
 template<class T> Vector<T>::Vector(const Block<T> &other, Int64 nr)
                   ^
/homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Vector.tcc:67:19: error:                 casa::Vector<T>::Vector(const casa::IPosition&, const T&)
 template<class T> Vector<T>::Vector(const IPosition& len, const T &initialValue)
                   ^
/homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Vector.tcc:61:19: error:                 casa::Vector<T>::Vector(size_t, const T&)
 template<class T> Vector<T>::Vector(size_t Length, const T &initialValue)
                   ^
/homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Vector.tcc:55:19: error:                 casa::Vector<T>::Vector(const casa::IPosition&)
 template<class T> Vector<T>::Vector(const IPosition& len)
                   ^
/homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Vector.tcc:49:19: error:                 casa::Vector<T>::Vector(size_t)
 template<class T> Vector<T>::Vector(size_t Length)
                   ^
/homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Vector.tcc:42:19: error:                 casa::Vector<T>::Vector()
 template<class T> Vector<T>::Vector()
                   ^
In file included from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Vector.h:325:0,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayUtil.h:34,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayLogical.tcc:32,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayLogical.h:453,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/MaskedArray.tcc:33,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/MaskedArray.h:738,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Array.tcc:32,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Array.h:842,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayMath.h:34,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayOpsDiffShapes.h:32,
                 from /homea/htb00/htb003/source/casacore/casa/Arrays/ArrayOpsDiffShapes.cc:27:
/homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Vector2.tcc:58:6: error: prototype for 'void casa::Array<T>::tovector(std::vector<T, U>&) const' does not match any in class 'casa::Array<T>'
 void Array<T>::tovector(vector<T, U> &out) const {
      ^
In file included from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayMath.h:34:0,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayOpsDiffShapes.h:32,
                 from /homea/htb00/htb003/source/casacore/casa/Arrays/ArrayOpsDiffShapes.cc:27:
/homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Array.h:328:15: error: candidates are: int casa::Array<T>::tovector() const
     vector<T> tovector() const;
               ^
/homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Array.h:326:10: error:                 template<class T> template<class U> void casa::Array<T>::tovector(vector<T, U>&) const
     void tovector(vector<T, U> &out) const;
          ^
In file included from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Array.h:842:0,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayMath.h:34,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayOpsDiffShapes.h:32,
                 from /homea/htb00/htb003/source/casacore/casa/Arrays/ArrayOpsDiffShapes.cc:27:
/homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Array.tcc:1057:11: error: prototype for 'std::vector<T> casa::Array<T>::tovector() const' does not match any in class 'casa::Array<T>'
 vector<T> Array<T>::tovector() const {
           ^
In file included from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayMath.h:34:0,
                 from /homea/htb00/htb003/source/casacore/casacore/casa/Arrays/ArrayOpsDiffShapes.h:32,
                 from /homea/htb00/htb003/source/casacore/casa/Arrays/ArrayOpsDiffShapes.cc:27:
/homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Array.h:328:15: error: candidates are: int casa::Array<T>::tovector() const
     vector<T> tovector() const;
               ^
/homea/htb00/htb003/source/casacore/casacore/casa/Arrays/Array.h:326:10: error:                 template<class T> template<class U> void casa::Array<T>::tovector(vector<T, U>&) const
     void tovector(vector<T, U> &out) const;
          ^
make[2]: *** [casa/CMakeFiles/casa_casa.dir/Arrays/ArrayOpsDiffShapes.cc.o] Error 1
make[1]: *** [casa/CMakeFiles/casa_casa.dir/all] Error 2
make: *** [all] Error 2

**Comment by tammojan** [comment]
You may want to have a look at #166

**Comment by fe56** [comment]
Indeed i wanted to have a look at that.
Sorry i missed it.

It works, thank you.
