### ISSUE TITLE
Build fails with gcc 4.8

### ISSUE THREAD

**Issue by GoogleCodeExporter** [casacore/casacore#61]
```
I have:

  $ g++ --version
  g++ (Debian 4.8.1-10) 4.8.1
  Copyright (C) 2013 Free Software Foundation, Inc.
  This is free software; see the source for copying conditions.  There is NO
  warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

My build of the current trunk (r21389) fails with:

  casacore/scimath/Functionals/SerialHelper.cc:69:52: error: declaration of ‘void casa::getArrayVal(V&, int, const casa::Record&, const casa::String&, casa::uInt) [with V = bool; casa::uInt = unsigned int]’ has a different exception specifier
                      const String& name, uInt index)WHATEVER_SUN_EXCEPTSPEC(InvalidSerializationError)

(See attached log)

WHATEVER_SUN_EXCEPTSPEC is defined (in casa/aipsdef.h) to be nothing, except on 
Sun or Cray XT3 machines. It's not obvious why: since getArrayVal() is defined 
(at scimath/Functionals/SerialHelper.h) with an exception specifier, I'm not 
sure why we'd want to hide it in SerialHelper.cc.

For what it's worth, the code builds fine on GCC 4.7; with clang 3.3 it raises 
warnings but still compiles.
```

Original issue reported on code.google.com by `jdswinb...@gmail.com` on 13 Sep 2013 at 2:34

Attachments:
- [casacore_r21389_gcc48.log](https://storage.googleapis.com/google-code-attachments/casacore/issue-61/comment-0/casacore_r21389_gcc48.log)
