### ISSUE TITLE
PR #658 build problem

### ISSUE THREAD

**Issue by vsuorant** [casacore/casacore#664]
Builds fail on EL6 after PR #658:
 
casacore/ms/apps/readms.cc:520:29: error: ‘omp_num_threads’ was not declared in this scope
   nthread = omp_num_threads();

**Comment by gervandiepen** [comment]
This has already been addressed.
Ger
