### ISSUE TITLE
failed make: libcasa_casa.so.2.3.0: undefined reference to `H5P_CLS_DATASET_ACCESS_ID_g'

### ISSUE THREAD

**Issue by mknapp55** [casacore/casacore#612]
Make fails with HDF5 enabled.  Cmake command:
```
[mknapp@eofe7 build]$ cmake -DUSE_FFTW3=ON -DDATA_DIR=/home/mknapp/cep3_software/cep/casacore/builds/casacore-2.3.0 -DUSE_OPENMP=ON -DUSE_HDF5=ON -DBUILD_PYTHON=ON -DUSE_THREADS=ON -DCMAKE_INSTALL_PREFIX=/home/mknapp/local_software/casacore/2.3 -DCFITSIO_ROOT_DIR=/home/mknapp/local_software/cfitsio_3410 -DWCSLIB_ROOT_DIR=/home/mknapp/local_software/wcslib-5.16 -DBoost_INCLUDE_DIR=/home/mknapp/local_software/boost/1_64_0/include -DHDF5_ROOT_DIR=/home/mknapp/local_modules/hdf5/1.8.9 -DHDF5_sz_LIBRARY_DEBUG=/home/mknapp/local_software/hdf5/1.8.19/lib -DHDF5_sz_LIBRARY_RELEASE=/home/mknapp/local_software/hdf5/1.8.19/lib ..
```
Make error:
```
[ 15%] Building CXX object casa/CMakeFiles/casa_casa.dir/version.cc.o
Linking CXX shared library libcasa_casa.so
[ 15%] Built target casa_casa
[ 15%] Building CXX object casa/apps/CMakeFiles/casahdf5support.dir/casahdf5support.cc.o
Linking CXX executable casahdf5support
../libcasa_casa.so.2.3.0: undefined reference to `H5P_CLS_DATASET_ACCESS_ID_g'
../libcasa_casa.so.2.3.0: undefined reference to `H5P_LST_LINK_ACCESS_ID_g'
../libcasa_casa.so.2.3.0: undefined reference to `H5P_CLS_DATASET_CREATE_ID_g'
../libcasa_casa.so.2.3.0: undefined reference to `H5P_CLS_FILE_CREATE_ID_g'
../libcasa_casa.so.2.3.0: undefined reference to `H5P_CLS_FILE_ACCESS_ID_g'
collect2: error: ld returned 1 exit status
make[2]: *** [casa/apps/casahdf5support] Error 1
make[1]: *** [casa/apps/CMakeFiles/casahdf5support.dir/all] Error 2
make: *** [all] Error 2
```

```
[mknapp@eofe7 build]$ module list
Currently Loaded Modulefiles:
  1) gcc/6.2.0                         4) boost/1_64_0                      7) lapack/3.7.1                     10) openmpi/2.0.1                    13) engaging/python/2.7.10(default)
  2) bison/3.0                         5) fftw/3.3.6                        8) log4cplus/1.2.1                  11) cfitsio/3410                     14) hdf5/1.8.9
  3) blas/3.7.1                        6) flex/2.6.4                        9) texinfo/4.5                      12) wcslib/5.16
```

**Comment by tammojan** [comment]
I think you don't need HDF5 support, try building with `-DUSE_HDF5=OFF`.

**Comment by mknapp55** [comment]
I worked with I built with HDF5 1.8.7 instead of 1.8.9.

**Comment by tammojan** [comment]
Thanks for reporting.

**Comment by gervandiepen** [comment]
This must be a problem with library paths. You can use 'make VERBOSE=1' to
see the exact link command.
Do you need to specify the HDF5 DEBUG and RELEASE paths? I never do that.

**Comment by mknapp55** [comment]
It may not be necessary to specify the HDF5 DEBUG and RELEASE paths - that was my attempt to overcome the error above and get rid of a bunch of warnings.  I'll try to run it with VERBOSE=1 tomorrow and post the outcome.
