### ISSUE TITLE
Casacore won't compile with gcc4.6/g++4.6

### ISSUE THREAD

**Issue by GoogleCodeExporter** [casacore/casacore#40]
```
Hello,


tried to compile casacore on a freshly installed Linux Mint system (essentially 
this is Debian Testing). The gcc/g++ versions are 4.6.1

Both using scons and cmake didn't work - there was the same error:

In file included from /opt/casacore-1.3.0/casa/Arrays/ArrayBase.h:34:0,
                 from /opt/casacore-1.3.0/casa/Arrays/Array.h:32,
                 from /opt/casacore-1.3.0/casa/Arrays/ArrayMath.h:34,
                 from /opt/casacore-1.3.0/casa/Arrays/Array2Math.cc:28:
/opt/casacore-1.3.0/casa/Arrays/IPosition.h:358:13: error: ‘ptrdiff_t’ does 
not name a type
In file included from /opt/casacore-1.3.0/casa/Arrays/Array.h:33:0,
                 from /opt/casacore-1.3.0/casa/Arrays/ArrayMath.h:34,
                 from /opt/casacore-1.3.0/casa/Arrays/Array2Math.cc:28:
/opt/casacore-1.3.0/casa/Containers/Block.h:310:11: error: ‘ptrdiff_t’ does 
not name a type
In file included from /opt/casacore-1.3.0/casa/Arrays/ArrayMath.h:34:0,
                 from /opt/casacore-1.3.0/casa/Arrays/Array2Math.cc:28:
/opt/casacore-1.3.0/casa/Arrays/Array.h:593:15: error: ‘ptrdiff_t’ does not 
name a type
/opt/casacore-1.3.0/casa/Arrays/Array.h:631:15: error: ‘ptrdiff_t’ does not 
name a type
make[2]: *** [casa/CMakeFiles/casa_casa.dir/Arrays/Array2Math.cc.o] Error 1
make[1]: *** [casa/CMakeFiles/casa_casa.dir/all] Error 2
make: *** [all] Error 2


Switching back to gcc/g++ v4.4 did the trick:

scons --with-cc=/usr/bin/gcc-4.4 --with-cxx=/usr/bin/g++-4.4 --prefix=/tmp 
--wcs-root=/opt/



Regards,

Enno

```

Original issue reported on code.google.com by `enno.mid...@gmail.com` on 23 Feb 2012 at 12:59
