### ISSUE TITLE
Not compiles with gcc-4.7.0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [casacore/casacore#51]
```
What steps will reproduce the problem?
1.Use gentoo sci-astronomy/casacore-1.4.0 ebuild and gcc-4.7.0
2.
3.

What is the expected output? What do you see instead?
Compiles and run fine.

Please provide any additional information below.

cd /var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0_build/casa 
&& /usr/bin/x86_64-pc-linux-gnu-g++  -Dcasa_casa_EXPORTS -DHAVE_HDF5 
-DHAVE_FFTW3 -DHAVE_FFTW3_THREADS -DHAVE_READLINE -DUSE_THREADS 
-DUSE_MULTI_THREADING  -DNDEBUG -O2 -pipe -ggdb -march=native  -pthread 
-fopenmp -fPIC 
-I/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0 
-I/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0_build    -o 
CMakeFiles/casa_casa.dir/Arrays/ArrayError.cc.o -c 
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/Ar
rayError.cc
In file included from 
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/Ar
rayBase.h:34:0,
                 from /var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/Array.h:32,
                 from /var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/ArrayUtil2.cc:33:
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:130:28: error: ‘ssize_t’ has not been declared
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:135:29: error: ‘ssize_t’ has not been declared
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:135:43: error: ‘ssize_t’ has not been declared
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:135:57: error: ‘ssize_t’ has not been declared
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:136:9: error: ‘ssize_t’ has not been declared
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:136:31: error: ‘ssize_t’ has not been declared
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:136:53: error: ‘ssize_t’ has not been declared
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:137:9: error: ‘ssize_t’ has not been declared
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:137:31: error: ‘ssize_t’ has not been declared
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:137:53: error: ‘ssize_t’ has not been declared
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:138:9: error: ‘ssize_t’ has not been declared
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:151:26: error: declaration of ‘operator=’ as non-function
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:151:24: error: expected ‘;’ at end of member declaration
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:151:34: error: expected ‘)’ before ‘value’
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:224:5: error: ‘ssize_t’ does not name a type
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:225:5: error: ‘ssize_t’ does not name a type
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:226:5: error: ‘ssize_t’ does not name a type
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:227:5: error: ‘ssize_t’ does not name a type
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:235:5: error: ‘ssize_t’ does not name a type
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:236:5: error: ‘ssize_t’ does not name a type
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:240:11: error: ‘ssize_t’ does not name a type
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:295:23: error: ‘ssize_t’ has not been declared
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:296:23: error: ‘ssize_t’ has not been declared
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:297:23: error: ‘ssize_t’ has not been declared
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:298:23: error: ‘ssize_t’ has not been declared
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:365:13: error: ‘ssize_t’ does not name a type
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:366:13: error: ‘ssize_t’ does not name a type
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:367:19: error: ‘ssize_t’ does not name a type
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:368:13: error: ‘value_type’ does not name a type
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:369:19: error: ‘value_type’ does not name a type
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:370:13: error: ‘value_type’ does not name a type
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:371:19: error: ‘value_type’ does not name a type
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:377:5: error: ‘iterator’ does not name a type
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:379:5: error: ‘const_iterator’ does not name a type
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:381:5: error: ‘iterator’ does not name a type
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:383:5: error: ‘const_iterator’ does not name a type
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:398:5: error: ‘ssize_t’ does not name a type
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h:401:5: error: ‘ssize_t’ does not name a type
/var/tmp/portage/sci-astronomy/casacore-1.4.0/work/casacore-1.4.0/casa/Arrays/IP
osition.h: In member function ‘void casa::IPosition::fill(casa::uInt, 
InputIterator)’:

Full build log attached.

Thank you in advance.

```

Original issue reported on code.google.com by `nheghath...@gmail.com` on 12 May 2012 at 9:36
