### ISSUE TITLE
dlmalloc macro gives compile errors on ppc64 (Ubuntu 16.04)

### ISSUE THREAD

**Issue by jjdmol** [casacore/casacore#696]
Casacore (both trunk and v2.4) fail to compile on Ubuntu 16.04.3 ppc64:
```
In file included from /usr/include/features.h:367:0,
                 from /usr/include/time.h:27,
                 from /tmp/src/casacore/casa/OS/malloc.cc:564:
/usr/include/stdlib.h:466:66: error: declaration of ‘void* malloc(size_t) throw ()’ has a different exception specifier
 extern void *malloc (size_t __size) __THROW __attribute_malloc__ __wur;
                                                                  ^
/tmp/src/casacore/casa/OS/malloc.cc:792:32: error: from previous declaration ‘void* malloc(size_t)’
 #define dlmalloc               malloc

/tmp/src/casacore/casa/OS/malloc.cc:823:7: note: in expansion of macro ‘dlmalloc’
 void* dlmalloc(size_t);
```

Similar errors are thrown for calloc/realloc/free, both from malloc.cc and Memory.cc.

**Comment by jjdmol** [comment]
Reason found, AIPS_LINUX is not defined, leading to the use of these code paths. Fix proposed in PR #699.

**Comment by tammojan** [comment]
Fixed by #699
