### ISSUE TITLE
cannot build with scons 1.0.1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [casacore/casacore#20]
```
I get the following error:

Building package: tables
scons  enable_hdf5=false prefix=/usr/local wcsroot=/usr/local install
casacoreroot=/usr/local
scons: Reading SConscript files ...

scons: warning: The env.Copy() method is deprecated; use the
env.Clone() method                                      instead.
File "/usr/local/share/casacore/buildenv.py", line 3, in BuildEnv
AttributeError: SConsEnvironment instance has no attribute 'CXXFile':
 File "/home/timba/Desktop/casacore-0.3.0/tables/SConstruct", line 66:
   duplicate=0, exports=["buildenv", "installer"])
 File "/usr/lib/scons-1.0.1.d20081001/SCons/Script/SConscript.py", line 536:
   return apply(_SConscript, [self.fs,] + files, subst_kw)
 File "/usr/lib/scons-1.0.1.d20081001/SCons/Script/SConscript.py", line 259:
   exec _file_ in call_stack[-1].globals
 File "/home/timba/Desktop/casacore-0.3.0/tables/tables/SConscript", line 9:
   ff = myenv.CXXFile(File(f), CXXFILESUFFIX=".lcc")


The only version I've been able to build with is 0.97. This is pretty bad,
because scons 1.0.1 is designated a "stable" release, and they don't even
offer 0.97 for download anymore. 
```

Original issue reported on code.google.com by `osmir...@gmail.com` on 7 Oct 2008 at 11:29
